name: Terraform Deploy
on:
    push:
        branches:
            - main
            - dev

permissions:
    id-token: write
    contents: read

jobs:
    Terraform:
        name: Terraform Deploy
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./Terrafrom/backend
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Sample Print Statements
              run: echo "Let us Deploy the Terraform Infrastructure..."

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::332665093871:role/GitHubActionsRole
                  aws-region: ap-south-1
                  audience: sts.amazonaws.com

            - name: Verify AWS Identity
              run: aws sts get-caller-identity

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              run: terraform init

            #- name: Terraform Import S3 Bucket
            #  run: terraform import aws_s3_bucket.terraform_state cde-terraform-state-dev || true

            #- name: Terraform Import S3 Versioning
            #  run: terraform import aws_s3_bucket_versioning.versioning cde-terraform-state-dev || true

            #- name: Terraform Import S3 Encryption
            #  run: terraform import aws_s3_bucket_server_side_encryption_configuration.encryption cde-terraform-state-dev || true

            #- name: Terraform Import DynamoDB Table
            #  run: terraform import aws_dynamodb_table.terraform_locks terraform-locks || true

            - name: Terraform Plan
              run: terraform plan

            - name: Terraform Apply
              run: terraform apply -auto-approve
