name: Test AWS OIDC Connection
on:
    push:
        branches:
            - main
            - dev
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    Test-Job:
        name: Test AWS OIDC Connection
        runs-on: ubuntu-latest
        environment: dev
        env:
            ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: ${{ vars.ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION }}
        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::332665093871:role/GitHubActionsRole
                  aws-region: ap-south-1
                  audience: sts.amazonaws.com

            - name: Verify AWS Identity
              run: aws sts get-caller-identity